ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  ServerCoordination-larkbot:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: This is FC service
      Role: 'acs:ram::1315976229694229:role/AliyunFcDefaultRole'
      LogConfig:
        Project: aliyun-fc-cn-hangzhou-200354cf-0c75-5f29-bf51-36dbee598257
        Logstore: function-log
      InternetAccess: true
    ServerCoordination-larkbot:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        Timeout: 120
        MemorySize: 1024
        InstanceConcurrency: 5
        EnvironmentVariables:
          APP_ID: '"cli_a392b9f8a4b8d00d"'
          APP_SECRET: '"jSMQG8yJ1G1zef82GAycwf8SGbrjDOVh"'
          LARK_HOOK: >-
            "https://open.feishu.cn/open-apis/bot/v2/hook/e5746240-60a1-443c-b8c1-eef212897305"
          LD_LIBRARY_PATH: >-
            /code/.fun/root/usr/local/lib:/code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code/.fun/root/lib:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/python/lib/python2.7/site-packages:/code/.fun/root/python/lib/python3.6/site-packages:/code:/code/lib:/usr/local/lib
          NODE_PATH: '/code/node_modules:/usr/local/lib/node_modules'
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code:/code/node_modules/.bin:/code/.fun/python/bin:/code/.fun/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin
          PYTHONUSERBASE: /code/.fun/python
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - GET
              - POST
              - PUT
